plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sam.catchgame'
    compileSdk 35

    defaultConfig {
        applicationId "com.sam.catchgame"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "2.1"
    }
}

dependencies {
    implementation 'com.android.billingclient:billing:9.1.0'
}


configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}
