plugins { id 'com.android.application' }
android {
    namespace 'com.sam.roninnightcity'
    compileSdk 36
    defaultConfig {
        applicationId "com.sam.roninnightcity"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug { debuggable false }
        release { minifyEnabled false; shrinkResources false }
    }
}
