plugins {
    id 'com.android.application'
}

android {
    namespace 'tj.baraka.store'
    compileSdk 36

    defaultConfig {
        applicationId 'tj.baraka.store'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            debuggable false
        }
    }
}
